# version: '3.8'

#docker-compose up --build
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    labels:
      - "monitoring=enabled"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  monitor-net:
    driver: bridge